#!/bin/bash
inputdata_root=/global/cfs/cdirs/e3sm/inputdata
e3sm_root=${HOME}/codes/e3sm/branches/master
atm_resolution=2
atm_grid_name=ne${atm_resolution}pg2
dyn_grid_name=ne${atm_resolution}
lnd_grid_name=${atm_grid_name}
ocn_grid_name=oQU480
ocn_grid_file="${inputdata_root}/ocn/mpas-o/oQU480/ocean.QU.480km.scrip.181106.nc"
output_root=/global/cfs/cdirs/e3sm/bhillma/grids/${atm_grid_name}
